### ISSUE TITLE
Meteor-additions is not letting the game run or crashing the game

### ISSUE THREAD

**Issue by Hyped1XGeek** [JFronny/MeteorAdditions#13]
When I run with meteor-additions as whole, the game doesn't start and gives this log file 
[latestestest-1.log](https://github.com/JFronny/MeteorAdditions/files/8774131/latestestest-1.log)

But for some reason when I remove `libjf-unsafe-v0-2.8.0.jar` from META-INF the game seems to run but then crashes with this crash report
[crash-2022-05-26_01.16.43-client.txt](https://github.com/JFronny/MeteorAdditions/files/8774142/crash-2022-05-26_01.16.43-client.txt)

Will you please help me out here?
:)

**Comment by JFronny** [comment]
libjf-unsafe is required for libjf-config, which is required for the translate subsystem. Although I'm not certain that this is the issue, there was a compatibility problem with the latest fabric loader versions (which you seem to be using) in libjf. This has since been fixed, but it seems you are still on an outdated version. Please try removing and redownloading MeteorAdditions, the updated version should be packaged in the latest release. If that doesn't work, try downloading the latest LibJF build from modrinth or curseforge separately

**Comment by Hyped1XGeek** [comment]
Adding the `LibJF` worked
Thanks :D

Great addon btw👍
