### ISSUE TITLE
[suggestion] .taco

### ISSUE THREAD

**Issue by playeur242** [JFronny/MeteorAdditions#22]
add the .taco from wurst client plsss

**Comment by JFronny** [comment]
Wurst uses a GPL3 license, while this project uses the MIT license.
Since I have not copied any code, that should be OK for now, but copying the taco graphic (as you requested) would constitute a license violation.
Therefore, this cannot (legally) be implemented, unless a graphic using a compatible license is provided.

**Comment by playeur242** [comment]
Hmm maybe you could make something to just display gif in general then?

**Comment by JFronny** [comment]
Rendering gifs in minecraft is a complicated problem I don't want to get into.
In case you didn't realize, Wurst just has a set of PNGs which are rendered in sequence.
This is probably more relevant to some HUD mod anyways.
